// src/const.events.ts
// Định nghĩa các loại event sử dụng trong extension

export enum TAOPROMPT_EVENTS {
  PROMPT_CREATE = 'TAOPROMPT_PROMPT_CREATE',
  PROMPT_STREAM_CHUNK = 'TAOPROMPT_PROMPT_STREAM_CHUNK',
  PROMPT_STREAM_DONE = 'TAOPROMPT_PROMPT_STREAM_DONE',
  PROMPT_ERROR = 'TAOPROMPT_PROMPT_ERROR',
  // 
  AUTH_REQUEST = 'TAOPROMPT_AUTH_REQUEST',
  AUTH_UPDATE = 'TAOPROMPT_AUTH_UPDATE',
  AUTH_SEND = 'SEND_AUTH',
  // 
  POPUP_OPEN = 'OPEN_POPUP',
  SETTINGS_UPDATE = 'TAOPROMPT_SETTINGS_UPDATE',
  // 
  LOADED = 'TAOPROMPT_LOADED'
}
